# Generated by Django 6.1.1 on 2026-09-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_department_employee_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='employee_images/'),
        ),
    ]
